name: Process Iconsets

on:
  workflow_dispatch:
  # schedule:
    # Runs twice daily at 00:00 UTC and 12:00 UTC
    # - cron: '0 0,12 * * *'

jobs:
  process-icons:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install Rokit
        run: |
          curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash
          echo "$HOME/.rokit/bin" >> $GITHUB_PATH

      - name: Trust Rokit Tools
        run: |
          rokit trust lune-org/lune
          rokit trust Sleitnick/rbxcloud

      - name: Install Rokit Tools
        run: rokit install

      - name: Install resvg
        run: cargo install resvg

      - name: Install alpha-bleed
        run: cargo install --git https://github.com/EgoMoose/alpha-bleed

      - name: Install oxipng
        run: cargo install oxipng

      - name: Download TexturePacker
        run: |
          wget https://libgdx-nightlies.s3.amazonaws.com/libgdx-runnables/runnable-texturepacker.jar
          chmod +x runnable-texturepacker.jar

      - name: Run Astralis Script
        env:
          RBLX_API_KEY: ${{ secrets.RBLX_API_KEY }}
          HOLDER_USER_ID: ${{ secrets.HOLDER_USER_ID }}
        run: lune run astralis.luau

      - name: Cleanup TexturePacker
        run: |
          echo "Cleaning up TexturePacker..."
          rm -f runnable-texturepacker.jar

      - name: Wait 15 minutes (scheduled runs only)
        if: github.event_name == 'schedule'
        run: |
          echo "Waiting 15 minutes before pushing to main... (Moderation purposes)"
          sleep 900

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: update iconset metadata"
            git push origin main
          fi
