name: Process Iconsets

on:
  workflow_dispatch:
    inputs:
      iconsets:
        description: 'Comma-separated list of iconset names (optional - uses script default if empty)'
        required: false
        type: string

jobs:
  process-icons:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rokit
        run: |
          curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash
          echo "$HOME/.rokit/bin" >> $GITHUB_PATH

      - name: Initialize Rokit
        run: rokit init

      - name: Install Lune
        run: rokit add lune

      - name: Install rbxcloud
        run: rokit add Sleitnick/rbxcloud

      - name: Install resvg
        run: cargo install resvg

      - name: Install alpha-bleed
        run: cargo install --git https://github.com/EgoMoose/alpha-bleed

      - name: Install oxipng
        run: cargo install oxipng

      - name: Download TexturePacker
        run: |
          wget https://libgdx-nightlies.s3.amazonaws.com/libgdx-runnables/runnable-texturepacker.jar
          chmod +x runnable-texturepacker.jar

      - name: Run Astralis Script
        env:
          RBLX_API_KEY: ${{ secrets.RBLX_API_KEY }}
          HOLDER_USER_ID: ${{ secrets.HOLDER_USER_ID }}
        run: lune run astralis.luau

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update iconset metadata'
          committer: GitHub Actions <actions@github.com>
          author: GitHub Actions <actions@github.com>
          branch: iconset-update-${{ github.run_number }}
          delete-branch: true
          title: '🌠 Update Iconset Metadata'
          body: |
            ## Iconset Processing Complete
            
            This PR was automatically generated by the Astralis iconset processing workflow.
            
            ### Changes
            - Updated `icons.json` with new iconset metadata
            - Processed iconsets and uploaded spritesheets to Roblox
            
            ### Details
            - **Workflow Run**: [${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - **Triggered by**: @${{ github.actor }}
          labels: |
            automated
            iconsets
          draft: false